grep 'decimals()' tokens/SecurityToken.sol
grep 'totalSupply()' tokens/SecurityToken.sol
grep 'balanceOf(address' tokens/SecurityToken.sol
grep 'allowance(address' tokens/SecurityToken.sol
grep 'transfer(address' tokens/SecurityToken.sol
grep 'transferFrom(address' tokens/SecurityToken.sol
grep 'approve(address' tokens/SecurityToken.sol
grep 'decreaseApproval(address' tokens/SecurityToken.sol
grep 'increaseApproval(address' tokens/SecurityToken.sol
grep 'canTransfer(address' tokens/SecurityToken.sol
grep 'canTransferFrom(address' tokens/SecurityToken.sol
grep 'setDocument(bytes32' tokens/SecurityToken.sol
grep 'removeDocument(bytes32' tokens/SecurityToken.sol
grep 'getDocument(bytes32' tokens/SecurityToken.sol
grep 'getAllDocuments()' tokens/SecurityToken.sol
grep 'isControllable()' tokens/SecurityToken.sol
grep 'isModule(address' tokens/SecurityToken.sol
grep 'issue(address' tokens/SecurityToken.sol
grep 'mintWithData(address' tokens/SecurityToken.sol
grep 'redeem(uint256' tokens/SecurityToken.sol
grep 'redeemFrom(address' tokens/SecurityToken.sol
grep 'checkPermission(address' tokens/SecurityToken.sol
grep 'getModule(address' tokens/SecurityToken.sol
grep 'getModulesByName(bytes32' tokens/SecurityToken.sol
grep 'getModulesByType(uint8' tokens/SecurityToken.sol
grep 'totalSupplyAt(uint256' tokens/SecurityToken.sol
grep 'balanceOfAt(address' tokens/SecurityToken.sol
grep 'createCheckpoint()' tokens/SecurityToken.sol
grep 'getCheckpointTimes()' tokens/SecurityToken.sol
grep 'getInvestors()' tokens/SecurityToken.sol
grep 'getInvestorsAt(uint256' tokens/SecurityToken.sol
grep 'iterateInvestors(uint256' tokens/SecurityToken.sol
grep 'currentCheckpointId()' tokens/SecurityToken.sol
grep 'dataStore()' tokens/SecurityToken.sol
grep 'changeDataStore(address' tokens/SecurityToken.sol
grep 'changeTreasuryWallet(address' tokens/SecurityToken.sol
grep 'withdrawERC20(address' tokens/SecurityToken.sol
grep 'changeModuleBudget(address' tokens/SecurityToken.sol
grep 'updateTokenDetails(string' tokens/SecurityToken.sol
grep 'changeGranularity(uint256' tokens/SecurityToken.sol
grep 'freezeTransfers()' tokens/SecurityToken.sol
grep 'unfreezeTransfers()' tokens/SecurityToken.sol
grep 'freezeIssuance()' tokens/SecurityToken.sol
grep 'addModuleWithLabel(' tokens/SecurityToken.sol
grep 'addModule(address' tokens/SecurityToken.sol
grep 'archiveModule(address' tokens/SecurityToken.sol
grep 'unarchiveModule(address' tokens/SecurityToken.sol
grep 'removeModule(address' tokens/SecurityToken.sol
grep 'setController(address' tokens/SecurityToken.sol
grep 'controllerTransfer(address' tokens/SecurityToken.sol
grep 'controllerRedeem(address' tokens/SecurityToken.sol
grep 'disableController()' tokens/SecurityToken.sol
grep 'getVersion()' tokens/SecurityToken.sol
grep 'getInvestorCount()' tokens/SecurityToken.sol
grep 'holderCount()' tokens/SecurityToken.sol
grep 'transferWithData(address' tokens/SecurityToken.sol
grep 'transferFromWithData(address' tokens/SecurityToken.sol
grep 'granularity()' tokens/SecurityToken.sol
grep 'isIssuable()' tokens/SecurityToken.sol
